apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::158936236798:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-ptb2K50c6GAw
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::158936236798:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-10T20:58:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1230"
  uid: a73b73dc-e613-4b3f-af7e-d2dc509a9110
